[package]
name = "granite"
version = "0.1.0"
edition = "2024"

[dependencies]
glam = { version = "0.30", features = ["bytemuck"] }
pollster = "0.4"
wgpu = "28.0"
winit = "0.30"

[dev-dependencies]
bytemuck = { version = "1.22", features = ["derive"] }
